#!/usr/bin/env python3
import sys
from lnmt.cli import whitelist, netplan, vlan_threshold, blacklist, settings

commands = {
    'whitelist': whitelist.main,
    'netplan': netplan.main,
    'vlan-threshold': vlan_threshold.main,
    'blacklist': blacklist.main,
    'settings': settings.main
}

def main():
    if len(sys.argv) < 2 or sys.argv[1] not in commands:
        print("Usage: lnmt <command> [args]")
        print("Available commands: " + ", ".join(commands.keys()))
        sys.exit(1)
    command = sys.argv[1]
    sys.argv = [sys.argv[0]] + sys.argv[2:]
    commands[command]()

if __name__ == "__main__":
    main()
